language: cpp
compiler: gcc
dist: xenial

addons:
        apt:
                package:
                        - gcc
                        - g++
                        - libc6-dev
                        - libc6
                        - gcc-multilib
                        - g++-multilib

script:
        - make
