language: cpp
compiler: gcc
dist: xenial

branches:
  only:
    - master

jobs:
  include:
    - stage: build
      name: "Build for Linux-i386"
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - gcc
            - g++
            - libc6-dev
            - libc6
            - gcc-multilib
            - g++-multilib
      script:
        - make clean
        - make
        - make install
      after_success:
        - export GITHUB_TOKEN=$GH_TOKEN
        - UPLOADTOOL_SUFFIX=linux32
        - cd devtools/bin
        - wget -c https://github.com/FWGS/uploadtool/raw/master/upload.sh
        - bash upload.sh vpc_linux
    - stage: build
      name: "Build for Windows-i386"
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH="$MSBUILD_PATH:$PATH"
        - cd utils/vpc/
        - MSBuild.exe vpc.sln
        - cd ../..
      after_success:
        - UPLOADTOOL_SUFFIX=win32
        - export GITHUB_TOKEN=$GH_TOKEN
        - cd utils/vpc/Debug/
        - wget -c https://github.com/FWGS/uploadtool/raw/master/upload.sh
        - bash upload.sh vpc.exe
